export const paises = [
    {nombre:"COLOMBIANO"},
    {nombre:"AFGANO"},
    {nombre:"ALBANO"},
    {nombre:"ALEMÁN"},
    {nombre:"ANDORRANO"},
    {nombre:"ANGOLANO"},
    {nombre:"ANTIGUANO"},
    {nombre:"ARGELINO"},
    {nombre:"ARGENTINO"},
    {nombre:"ARMENIO"},
    {nombre:"AUSTRALIANO"},
    {nombre:"AUSTRIACO"},
    {nombre:"AZERBAIYANO"},
    {nombre:"BAHAMEÑO"},
    {nombre:"BANGLADESÍ"},
    {nombre:"BARBADENSE"},
    {nombre:"BAREINÍ"},
    {nombre:"BELGA"},
    {nombre:"BELICEÑO"},
    {nombre:"BENINÉS"},
    {nombre:"BIELORUSO"},
    {nombre:"BIRMANO"},
    {nombre:"BOLIVIANO"},
    {nombre:"BOSNIO"},
    {nombre:"BOTSUANO"},
    {nombre:"BRASILEÑO"},
    {nombre:"BRITÁNICO"},
    {nombre:"BRUNEANO"},
    {nombre:"BÚLGARO"},
    {nombre:"BURKINÉS"},
    {nombre:"BURUNDÉS"},
    {nombre:"CABOVERDIANO"},
    {nombre:"CAMBOYANO"},
    {nombre:"CAMERUNÉS"},
    {nombre:"CANADIENSE"},
    {nombre:"CEILANDÉS"},
    {nombre:"CENTROAFRICANO"},
    {nombre:"CHADIANO"},
    {nombre:"CHECO"},
    {nombre:"CHILENO"},
    {nombre:"CHINO"},
    {nombre:"CHIPRIOTA"},
    {nombre:"COMORENSE"},
    {nombre:"CONGOLEÑO"},
    {nombre:"COSTARRICENSE"},
    {nombre:"CROATA"},
    {nombre:"CUBANO"},
    {nombre:"DANÉS"},
    {nombre:"DOMINICANO"},
    {nombre:"DOMINIQUÉS"},
    {nombre:"ECUATOGUINEANO"},
    {nombre:"ECUATORIANO"},
    {nombre:"EGIPCIO"},
    {nombre:"ERITREO"},
    {nombre:"ESLOVACO"},
    {nombre:"ESLOVACO"},
    {nombre:"ESPAÑOL"},
    {nombre:"ESTADUNIDENSE"},
    {nombre:"ESTONIO"},
    {nombre:"ETÍOPE"},
    {nombre:"FILIPINO"},
    {nombre:"FINÉS"},
    {nombre:"FRANCÉS"},
    {nombre:"GABONÉS"},
    {nombre:"GAMBIANO"},
    {nombre:"GEORGIANO"},
    {nombre:"GHANÉS"},
    {nombre:"GRANADINO"},
    {nombre:"GRECO-CHIPRIOTA"},
    {nombre:"GRIEGO"},
    {nombre:"GROENLANDÉS"},
    {nombre:"GUAÑANO"},
    {nombre:"GUATEMALTECO"},
    {nombre:"GUINEANO"},
    {nombre:"GUINEANO"},
    {nombre:"HAITIANO"},
    {nombre:"HOLANDÉS"},
    {nombre:"HONDUREÑO"},
    {nombre:"HÚNGARO"},
    {nombre:"INDIO"},
    {nombre:"INDIONISIO"},
    {nombre:"IRANÍ"},
    {nombre:"IRAQUÍ"},
    {nombre:"IRLANDÉS"},
    {nombre:"ISLANDÉS"},
    {nombre:"ISRAELÍ"},
    {nombre:"ITALIANO"},
    {nombre:"JAMAICANO"},
    {nombre:"JAPONÉS"},
    {nombre:"JEMENÍ"},
    {nombre:"JORDANO"},
    {nombre:"KATARÍ"},
    {nombre:"KAZAJO"},
    {nombre:"KENIATA"},
    {nombre:"KIRGUÍS"},
    {nombre:"KIRIBATIANO"},
    {nombre:"KUWAITÍ"},
    {nombre:"LAOSIANO"},
    {nombre:"LESOTENSE"},
    {nombre:"LETONIO"},
    {nombre:"LIBANÉS"},
    {nombre:"LIBERIANO"},
    {nombre:"LIBIO"},
    {nombre:"LIECHTENSTEINIANO"},
    {nombre:"LITUANO"},
    {nombre:"LUXEMBURGÉS"},
    {nombre:"MACEDONIO"},
    {nombre:"MALAUÍ"},
    {nombre:"MALAYO"},
    {nombre:"MALDIVO"},
    {nombre:"MALGACHE"},
    {nombre:"MALIENSE"},
    {nombre:"MALTÉS"},
    {nombre:"MARFILEÑO"},
    {nombre:"MARROQUÍ"},
    {nombre:"MARSHALÉS"},
    {nombre:"MAURICIANO"},
    {nombre:"MAURITANO"},
    {nombre:"MEXICANO"},
    {nombre:"MOLDAVO"},
    {nombre:"MONAQUÉS"},
    {nombre:"MONGÓL"},
    {nombre:"MONTENEGRINO"},
    {nombre:"MOZAMBIQUEÑO"},
    {nombre:"NAMIBIO"},
    {nombre:"NAURUANO"},
    {nombre:"NEOZELANDÉS"},
    {nombre:"NICARAGUENSE"},
    {nombre:"NIGERIANO"},
    {nombre:"NIUANO"},
    {nombre:"NORCOREANO"},
    {nombre:"NORUEGO"},
    {nombre:"OMANÉS"},
    {nombre:"PAKISTANÍ"},
    {nombre:"PANAMEÑO"},
    {nombre:"PAPÚ"},
    {nombre:"PARAGUAYO"},
    {nombre:"PERUANO"},
    {nombre:"POLACO"},
    {nombre:"PORTUGUÉS"},
    {nombre:"RUANDÉS"},
    {nombre:"RUMANO"},
    {nombre:"RUSO"},
    {nombre:"SALOMONENSE"},
    {nombre:"SALVADOREÑO"},
    {nombre:"SAMOANO"},
    {nombre:"SANMARINENSE"},
    {nombre:"SANVICENTINO"},
    {nombre:"SAUDÍ"},
    {nombre:"SENEGALÉS"},
    {nombre:"SERBIO"},
    {nombre:"SEYCHELENSE"},
    {nombre:"SIERRALEONÉS"},
    {nombre:"SINGAPURENSE"},
    {nombre:"SIRIO"},
    {nombre:"SOMALÍ"},
    {nombre:"SUAZI"},
    {nombre:"SUDAFRICANO"},
    {nombre:"SUDANÉS"},
    {nombre:"SUECO"},
    {nombre:"SUIZO"},
    {nombre:"SURCOREANO"},
    {nombre:"SURINAMÉS"},
    {nombre:"TAILANDÉS"},
    {nombre:"TANZANO"},
    {nombre:"TIMORENSE"},
    {nombre:"TOGOLÉS"},
    {nombre:"TONGANO"},
    {nombre:"TUNECINO"},
    {nombre:"TURCO"},
    {nombre:"TUVALUANO"},
    {nombre:"UCRANIANO"},
    {nombre:"UGANDÉS"},
    {nombre:"URUGUAYO"},
    {nombre:"UZBECO"},
    {nombre:"VANUATUENSE"},
    {nombre:"VATICANO"},
    {nombre:"VENEZOLANO"},
    {nombre:"VIETNAMITA"},
    {nombre:"ZAMBIANO"},
    {nombre:"ZIMBABUENSE"},
]; 


export const estadoLegalizacion=[
   {estado:"Completo"},
   {estado:"Incompleto"},
   {estado:"Sin Envio"},
   {estado:"No continua"}
]

export const tipoDocumento=[
    {nombre:"Cédula de Ciudadania",abreviacion:"CC"},
    {nombre:"Tarjeta de Identidad",abreviacion:"TI"},
    {nombre:"Pasaporte",abreviacion:"P"},
    {nombre:"Cédula de Extranjeria",abreviacion:"CE"}
]

export const Rango=[
  {rango: "A"},
  {rango: "AA"},
  {rango: "AAA"}
]

export const Convenio=[
    {tipo:"Internacional Colombia"},
    {tipo:"Individual"}
]

export const Tipo=[
    {tipo:"Voluntario"},
    {tipo: "Practicante"}
]

export const Modalidad=[
    {tipo:"Virtual"},
    {tipo:"Mixta"},
    {tipo:"Presencial"}
]

export const Proyecto=[
    {tipo:"Construyendo Sueños"},
    {tipo:"Pintando Sueños"},
    {tipo:"Jornada Ambiental"},
    {tipo:"Ecoespacios"}
]

export const Formativa=[
    {tipo:"Acciones de Aspiracion"},
    {tipo:"Curso Completo Especial"},
    {tipo:"Proceso de Formacion Interno"},
]

export const Rol=[
    {tipo:"Lider de Cuadrilla"},
    {tipo:"Responsable de refrigerios"},
    {tipo:"Responsable Voluntariado"},
    {tipo:"Responsable de Herramientas"},
    {tipo:"Responsable Social"},
    {tipo:"Voluntario Constructor"},
    {tipo:"Apoyo tecnico en cuadrilla"},
    {tipo:"Apoyo social en cuadrilla"},
    {tipo:"Observador FCM"},
]

export const estadoActividad=[
    {estado: "Programado"},
    {estado: "Realizado"}
    
]