export const paises = [
    {nombre:"COLOMBIA"},
    {nombre:"AFGANISTÁN"},
    {nombre:"ALBANIA"},
    {nombre:"ALEMANIA"},
    {nombre:"ANDORRA"},
    {nombre:"ANGOLA"},
    {nombre:"ANTIGUA Y BARBUDA"},
    {nombre:"ARABIA SAUDITA"},
    {nombre:"ARGELIA"},
    {nombre:"ARGENTINA"},
    {nombre:"ARMENIA"},
    {nombre:"AUSTRALIA"},
    {nombre:"AUSTRIA"},
    {nombre:"AZERBAIYÁN"},
    {nombre:"BAHAMAS"},
    {nombre:"BANGLADÉS"},
    {nombre:"BARBADOS"},
    {nombre:"BARÉIN"},
    {nombre:"BÉLGICA"},
    {nombre:"BELICE"},
    {nombre:"BENIN"},
    {nombre:"BIELORRUSIA"},
    {nombre:"BOLIVIA"},
    {nombre:"BOSNIA Y HERZEGOVINA"},
    {nombre:"BOTSUANA"},
    {nombre:"BRASIL"},
    {nombre:"BRUNEI"},
    {nombre:"BULGARIA"},
    {nombre:"BURKINA FASO"},
    {nombre:"BURUNDI"},
    {nombre:"BUTÁN"},
    {nombre:"CABO VERDE"},
    {nombre:"CAMBOYA"},
    {nombre:"CAMERÚN"},
    {nombre:"CANADÁ"},
    {nombre:"CATAR"},
    {nombre:"CHAD"},
    {nombre:"CHILE"},
    {nombre:"CHINA"},
    {nombre:"CHIPRE"},
    {nombre:"COMORAS"},
    {nombre:"COREA DEL NORTE"},
    {nombre:"COREA DEL SUR"},
    {nombre:"COSTA DE MARFIL"},
    {nombre:"COSTA RICA"},
    {nombre:"CROACIA"},
    {nombre:"CUBA"},
    {nombre:"DINAMARCA"},
    {nombre:"DOMINICA"},
    {nombre:"ECUADOR"},
    {nombre:"EGIPTO"},
    {nombre:"EL SALVADOR"},
    {nombre:"EMIRATOS ARABES UNIDOS"},
    {nombre:"ERITREA"},
    {nombre:"ESLOVAQUIA"},
    {nombre:"ESLOVENIA"},
    {nombre:"ESPAÑA"},
    {nombre:"ESTADOS UNIDOS"},
    {nombre:"ESTONIA"},
    {nombre:"ETIOPÍA"},
    {nombre:"FILIPINAS"},
    {nombre:"FINLANDIA"},
    {nombre:"FIYI"},
    {nombre:"FRANCIA"},
    {nombre:"GABÓN"},
    {nombre:"GAMBIA"},
    {nombre:"GEORGIA"},
    {nombre:"GHANA"},
    {nombre:"GRANADA"},
    {nombre:"GRECIA"},
    {nombre:"GUATEMALA"},
    {nombre:"GUINEA"},
    {nombre:"GUINEA ECUATORIAL"},
    {nombre:"GUINEA-BISSAU"},
    {nombre:"GUYANA"},
    {nombre:"HAITÍ"},
    {nombre:"HONDURAS"},
    {nombre:"HUNGRÍA"},
    {nombre:"INDIA"},
    {nombre:"INDONESIA"},
    {nombre:"IRÁN"},
    {nombre:"IRAQ"},
    {nombre:"IRLANDA"},
    {nombre:"ISLANDIA"},
    {nombre:"ISLAS MARSHALL"},
    {nombre:"ISLAS SALOMÓN"},
    {nombre:"ISRAEL"},
    {nombre:"ITALIA"},
    {nombre:"JAMAICA"},
    {nombre:"JAPÓN"},
    {nombre:"JORDANIA"},
    {nombre:"KAZAJISTÁN"},
    {nombre:"KENIA"},
    {nombre:"KIRGUISTÁN"},
    {nombre:"KIRIBATI"},
    {nombre:"KUWAIT"},
    {nombre:"LAOS"},
    {nombre:"LESOTO"},
    {nombre:"LETONIA"},
    {nombre:"LÍBANO"},
    {nombre:"LIBERIA"},
    {nombre:"LIBIA"},
    {nombre:"LIECHTENSTEIN"},
    {nombre:"LITUANIA"},
    {nombre:"LUXEMBURGO"},
    {nombre:"MADAGASCAR"},
    {nombre:"MALASIA"},
    {nombre:"MALAUI"},
    {nombre:"MALDIVAS"},
    {nombre:"MALI"},
    {nombre:"MALTA"},
    {nombre:"MARRUECOS"},
    {nombre:"MAURICIO"},
    {nombre:"MAURITANIA"},
    {nombre:"MÉXICO"},
    {nombre:"MICRONESIA"},
    {nombre:"MOLDAVIA"},
    {nombre:"MÓNACO"},
    {nombre:"MONGOLIA"},
    {nombre:"MONTENEGRO"},
    {nombre:"MOZAMBIQUE"},
    {nombre:"MYANMAR (BIRMANIA)"},
    {nombre:"NAMIBIA"},
    {nombre:"NAURU"},
    {nombre:"NEPAL"},
    {nombre:"NICARAGUA"},
    {nombre:"NÍGER"},
    {nombre:"NIGERIA"},
    {nombre:"NORUEGA"},
    {nombre:"NUEVA ZELANDA"},
    {nombre:"OMÁN"},
    {nombre:"PAÍSES BAJOS"},
    {nombre:"PAKISTÁN"},
    {nombre:"PALAOS"},
    {nombre:"PALESTINA"},
    {nombre:"PANAMÁ"},
    {nombre:"PAPÚA NUEVA GUINEA"},
    {nombre:"PARAGUAY"},
    {nombre:"PERÚ"},
    {nombre:"POLONIA"},
    {nombre:"PORTUGAL"},
    {nombre:"PUERTO RICO"},
    {nombre:"REINO UNIDO"},
    {nombre:"REPÚBLICA CENTROAFRICANA"},
    {nombre:"REPÚBLICA CHECA"},
    {nombre:"REPÚBLICA DE MACEDONIA"},
    {nombre:"REPÚBLICA DEL CONGO"},
    {nombre:"REPÚBLICA DEMOCRÁTICA DEL CONGO"},
    {nombre:"REPÚBLICA DOMINICANA"},
    {nombre:"RUANDA"},
    {nombre:"RUMANIA"},
    {nombre:"RUSIA"},
    {nombre:"SAMOA"},
    {nombre:"SAN CRISTÓBAL Y NIEVES"},
    {nombre:"SAN MARINO"},
    {nombre:"SAN VICENTE Y LAS GRANADINAS"},
    {nombre:"SANTA LUCÍA"},
    {nombre:"SANTO TOMÉ Y PRÍNCIPE"},
    {nombre:"SENEGAL"},
    {nombre:"SERBIA"},
    {nombre:"SEYCHELLES"},
    {nombre:"SIERRA LEONA"},
    {nombre:"SIRIA"},
    {nombre:"SOMALIA"},
    {nombre:"SRI LANKA"},
    {nombre:"SUAZILANDIA"},
    {nombre:"SUDÁFRICA"},
    {nombre:"SUDÁN"},
    {nombre:"SUDÁN DEL SUR"},
    {nombre:"SUECIA"},
    {nombre:"SUIZA"},
    {nombre:"SURINAM"},
    {nombre:"TAILANDIA"},
    {nombre:"TANZANIA"},
    {nombre:"TAYIKISTÁN"},
    {nombre:"TIMOR ORIENTAL"},
    {nombre:"TOGO"},
    {nombre:"TONGA"},
    {nombre:"TRINIDAD Y TOBAGO"},
    {nombre:"TÚNEZ"},
    {nombre:"TURKMENISTÁN"},
    {nombre:"TURQUÍA"},
    {nombre:"TUVALU"},
    {nombre:"UCRANIA"},
    {nombre:"UGANDA"},
    {nombre:"URUGUAY"},
    {nombre:"UZBEKISTÁN"},
    {nombre:"VANUATU"},
    {nombre:"VENEZUELA"},
    {nombre:"VIETNAM"},
    {nombre:"YEMEN"},
    {nombre:"YIBUTI"},
    {nombre:"ZAMBIA"},
    {nombre:"ZIMBABUE"},
    
]; 

export const tipoDocumento=[
    {nombre:"Cédula de Ciudadania",abreviacion:"CC"},
    {nombre:"Tarjeta de Identidad",abreviacion:"TI"},
    {nombre:"Pasaporte",abreviacion:"P"},
    {nombre:"Cédula de Extranjeria",abreviacion:"CE"}
]

export const Rango=[
  {rango: "A"},
  {rango: "AA"},
  {rango: "AAA"}
]

export const Convenio=[
    {tipo:"Internacional Colombia"},
    {tipo:"Individual"}
]

export const Tipo=[
    {tipo:"Voluntario"},
    {tipo: "Practicante"}
]

export const Modalidad=[
    {tipo:"Virtual"},
    {tipo:"Mixta"},
    {tipo:"Presencial"}
]